name: Build against JDKs
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '21' ]
        architecture: [ 'x64' ]
    name: Build with JDK ${{ matrix.java }} on ${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          architecture: ${{ matrix.architecture }}

      - name: Install contract stubs
        working-directory: movie-descriptions
        run: mvn install

      - name: Build with Maven
        run: mvn verify

      - name: Build Docker image
        working-directory: movie-descriptions
        run: docker build -t movie-descriptions .

      - name: Run movie-descriptions
        run: docker run -d -p 8082:8082 movie-descriptions

      - name: Run tests
        working-directory: movie-descriptions
        run: ./blackbox.sh

